### ISSUE TITLE
Extract embedded subtitles?

### ISSUE THREAD

**Issue by Kezxo** [BrianDMG/conv2mp4-ps#1]
Looks like the script does not care about embedded subtitle tracks as it is now, any chance it could extract them as .srt files or maybe even embed them back into the new files?

EDIT: Looks like multiple audiotracks isn't working either.

**Comment by BrianDMG** [comment]
Hey Kezxo,

v1.4 (just uploaded) keeps all audio and subtitle tracks. I've had a limited number of files to test this out on, but it's worked perfectly on every file I've tested it on so I don't anticipate any major issues. Test it out on a few files before putting it in to production on your entire library.

**Comment by Saltystew** [comment]
Been using this since you posted on /r/plex, and since this update have tried it on an anime episode. It didn't do anything with the subtitles, they were either removed or ignored and lost in conversion, according to log files the ffmpeg conversion failed and it fell over to handbrake and the end result is a noticeable reduction of quality, scenes with lots of movement are extremely pixelated and even the still scenes have noticeable pixels in them. The original file did not. 

All of my previous usages with this script have worked out with ffmpeg and never fell down to handbrake so I assume the problem is there. As for the subtitles, for srt embedded subtitles in an mkv, it didn't work.

**Comment by BrianDMG** [comment]
Did you see any errors in the console from ffmpeg indicating why it might have failed? Or from Handbrake indicating why it might not have carried over the subtitle track? I was also testing it against an MKV with a single video channel, 2 audio channels, and a single subtitle track that I had converted directly from a VOB without issue. The MKVs of Stranger Things I (also) tested against did fail over to Handbrake, but all encoded everything properly and even looked pretty good on my 42" TV.

**Comment by Saltystew** [comment]
Actually it was just my computer being dumb, for some reason Microsoft visual studio messes with it and I had it installed for something. I uninstalled it and had no more problems, it kept saying something about a conflicting debugger or something. Sorry for the confusion.

Maybe on something that you could help me with, how would I put two different directories for the media path? Separate by comma or something else?
