### ISSUE TITLE
Could you add a way to call audio filters in the script?

### ISSUE THREAD

**Issue by hwwilliams** [BrianDMG/conv2mp4-ps#21]
So I've been digging around and finally found that ffmpeg can do audio normalization and it can be done using audio filters

https://ffmpeg.org/ffmpeg-filters.html#Audio-Filters

One such filter I'd like to be able to do is loudnorm

https://ffmpeg.org/ffmpeg-filters.html#loudnorm

If you don't want to implement this or if its just to much trouble I'll understand of course, just thought it'd be a nice feature as I've run across tons of files that just don't get loud enough or are too loud.

All I'm really wondering is if there'd be a way to add a section in the variables where I could add something like 'loudnorm -i -25' and it'd pass that to ffmpeg's audio filter.

**Comment by BrianDMG** [comment]
Hey, sorry for the (extreme) delay in responding, it's been a really hectic summer/autumn so far. I looked at the documentation you provided (thanks for the links), and while this seems like a good feature, it would _significantly_ increase the amount of time the script takes to complete because ffmpeg first has to scan the entire file in order to determine the norm level. I haven't ruled this out yet since it's something that even _I_ would like to see. It's not going to be a small change, though, so it may not make the next release (and will also take time to test). I have a baby due in early November, and finals for my last semester of university right after that, so time is going to be a luxury for a while.

**Comment by Saltystew** [comment]
Totally understand, no pressure or anything. Just as you said, I thought it'd be a nice feature and funny this is I haven't actually had a problem with audio levels on a file for awhile now anyway.

Congrats on the kid.

**Comment by BrianDMG** [comment]
I might write a different script to address this, but I don't think I'm going to implement it in this script since it's outside the scope of "lessening transcodes".
