### ISSUE TITLE
Script is already running in another instance. Waiting...

### ISSUE THREAD

**Issue by LilChippyD** [BrianDMG/conv2mp4-ps#41]
"Created a backup of C:\Users\User\Desktop\conv2mp4-ps-3.1.2\cfg_conv2mp4-ps.ps1
Script is already running in another instance. Waiting..."

Hey, I got this working perfectly last night then Windows upgraded to 1903 overnight. Not sure if previous script finished or not but now I'm left with this when starting the script.

**Comment by BrianDMG** [comment]
Assuming you've already got this figured out due to how long ago you posted this, but this can happen if the script is forcibly closed while executing. When the script starts executing, it creates a lock file (conv2mp4-ps.lock) in the directory the script is in. While that lock file exists, no new instances of the script can execute (this saves your CPU from getting bogged down with multiple intensive ffmpeg instances). Deleting the lock file will allow the script to execute once again.
