### ISSUE TITLE
More than one media path?

### ISSUE THREAD

**Issue by Saltystew** [BrianDMG/conv2mp4-ps#9]
I was curious if there's a way to add more than one media path to check for files to convert?

**Comment by BrianDMG** [comment]
There's no way to natively add another path in the script, but if you created a copy of the script, pointed it at a different media path, and changed the log path, you could run it against a separate path. Unless you have a beast of a machine, I'd recommend running the scripts sequentially instead of concurrently. Two instances of ffmpeg or Handbrake encoding video at the same time is going to be pretty hard on a system.
